""" a module to define the function to check media passed to the backend
this module checks if the media is generated by ai"""

import json
import requests as re
from typing import List
from fastapi import UploadFile

from utils.settings import settings

async def image_fraud_checker(image_url: str):
    """ a function to check if an uploaded image is ai generated or not
    Args:
        image_url: the url of the image to check
    """

    request = re.get("https://api.sightengine.com/1.0/check.json", {
            "url": image_url,
            "models": "genai",
            "api_user": settings.sightengine_api_user,
            "api_secret": settings.sightengine_api_secret
        })
    
    return json.loads(request.text)

async def video_fraud_checker(video_url: str, video_media: UploadFile):

    return {"message": "this is a video file and we are not checking it yet, but we will in the future"}
